#!/bin/bash

#********************************************
# * Cagent monitoring Plugin for Plesk Panel
# * @Author:   Artur Troian troian dot ap at gmail dot com
# * @Author:   cloudradar GmbH
# * @Copyright: (c) 2019
#********************************************

# fail if command return is no 0
set -e

# fail if dereferencing variable is not set
set -u

set -o pipefail

die () {
    echo "$@" 1>&2;
    exit 1
}

do_install () {
    case "$1" in
        rpm)
            rpm -i $2
        ;;
        deb)
            dpkg -i $2
        ;;
    esac
}

do_uninstall () {
    set +e
    case $1 in
        rpm)
            rpm -e cagent
        ;;
        deb)
            apt-get remove --purge cagent -y
        ;;
    esac

    rm -rf /etc/cagent
    rm -rf /var/log/cagent/
}

if [[ "${1:-}" = "uninstall" ]]; then
    do_uninstall $2
elif [[ "${1:-}" = "install" ]]; then
    do_install $2 $3
else
    die "unknown command"
fi

