#!/bin/bash

#********************************************
# * Cagent monitoring Plugin for Plesk Panel
# * @Author:   Anton Gribanov anton dot gribanov at gmail dot com
# * @Author:   cloudradar GmbH
# * @Copyright: (c) 2019
#********************************************

# fail if command return is no 0
set -e

# fail if dereferencing variable is not set
set -u

set -o pipefail

rpm -i $1