#!/bin/bash

#********************************************
# * Cagent monitoring Plugin for Plesk Panel
# * @Author:   Artur Troian troian dot ap at gmail dot com
# * @Author:   cloudradar GmbH
# * @Copyright: (c) 2019
#********************************************

set -eu

/usr/bin/cagent ${@}